export ZSH="$HOME/.oh-my-zsh"
export ZSH_THEME="robbyrussell"

plugins=(git zsh-pyenv zsh-autosuggestions zsh-syntax-highlighting)

source $ZSH/oh-my-zsh.sh


[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# eval "$(pyenv init -)"
